services:
  php:
    image: php:apache
    ports:
      - 80:80
    volumes:      
      # - C:\Users\video\Pictures\:/var/www/html/media
      - ./MediaTemp/:/var/www/html/media
      - ./:/var/www/html/
    expose:
      - 9000